### ISSUE TITLE
FOV algorithm checks Y against map.width instead of map.height when scanning w2sw

### ISSUE THREAD

**Issue by mcccclean** [amethyst/bracket-lib#204]
Hello! I've been going through the roguelike tutorial and have been having an absolute blast, thank you so much for putting this all together! It's absolutely incredible.

I've noticed that on a map that is taller than it is wide, the FOV algorithm is checking the wrong dimensions for W2SW.

![image](https://user-images.githubusercontent.com/2935841/116016271-79d52000-a67f-11eb-9745-f4978dca182f.png)

I've located the offending line - will have a PR up shortly.

**Comment by LEGOL2** [comment]
Hello!
I know this should not be discussed in pull request, but how did you use a sprite in your game?

**Comment by mcccclean** [comment]
@LEGOL2 I haven't used sprites really 😅 - I have just edited the font to replace some of the glyphs. So where it's showing the little guy, he is really an `É`, and the parcel is actually a `≡`.

To use a custom font, it looks something like this (you will have to edit it to use the right dimensions and tile size for your game):

```rust
rltk::embedded_resource!(FONT, "../resources/cp437.png");

fn main() -> rltk::BError {
    let mut gs = State::new();
    gs.register_components();
    raws::load_raws();
    gs.insert_resources();

    let (w, h) = (80, 60);
    rltk::link_resource!(FONT, "resources/cp437.png");
    let context = rltk::RltkBuilder::new()
        .with_dimensions(w, h)
        .with_tile_dimensions(16, 16)
        .with_font("cp437.png", 16, 16)
        .with_simple_console(w, h, "cp437.png")
        .build()?;

    rltk::main_loop(context, gs)
}
```

**Comment by thebracket** [comment]
Sorry about the delay in looking at this; I've been snowed under with book release stuff (Hands-on Rust final ebook/paper release is coming up in June, and there's an amazing amount of work that goes into the launch) and quite unwell for a bit. I'll take a look at the PR - thanks!

@LEGOL2 
There's actually a few ways to go about putting sprites in:

* You can use a custom font file, replacing character/glyphs with custom graphics. [Flappy Dragon - Bonus Edition](https://hands-on-rust.com/2021/02/08/from-flappy-dragon-to-flappy-bonus/) from *Hands-on Rust* uses this (as does the dungeon crawler game in the book). You can also check out the `tiles` example in the `bracket-terminal` source's examples directory for a simple version.
* You can use sprite layers. They aren't as flexible as I want them to be yet, but they are getting there. The big limitation right now is one sprite sheet per sprite layer - so you have to pack all your sprites into one graphic and use a sprite sheet (this limitation is there because changing texture bindings in OpenGL is slow, and there are some nasty render-order issues to resolve to avoid having to change the pipeline for each sprite). You can see an example of it in action in the `sprites` example, also in bracket-terminal's examples directory.

Writing a bit more sprite support is definitely on the menu, but I'm having to move a little slowly right now due to all my other commitments.
