### ISSUE TITLE
z-order not in draw_batch.set

### ISSUE THREAD

**Issue by Th3Kh3d1v3** [amethyst/bracket-lib#225]
I noticed that in bracket-terminal draw_batch.set_fancy has a z-order but uses PointF, while draw_batch.set does not have a z-order at all.

This ends up with the Player being rendered underneath items when they are standing over them. Could z-order be added as an optional argument to draw_batch.set?

**Comment by Th3Kh3d1v3** [comment]
The issue is from the roguelike game made in the book, "Hands-on Rust."

**Comment by thebracket** [comment]
Ok, I'm working on a branch that supports something similar (issue_225_z_order). You can't overload functions in Rust with optional parameters, so I've added a `with_z` suffixed version of the draw commands. Otherwise, order is as-specified. So to `set` on top, you'd call `set_with_z` and put a large number as the last parameter.

It still needs testing and an example for how to use it.
