### ISSUE TITLE
Weird white lines all across screen

### ISSUE THREAD

**Issue by BradFitz66** [amethyst/bracket-lib#273]
Trying to use bracket-lib with Bevy but come across some quite severe graphical issues. The main one being that there's a bunch of small white lines all across the screen

![](https://cdn.discordapp.com/attachments/990261155463319572/990643915193454662/unknown.png)

I've tried everything from setting Image filtering to Nearest as images are created but that didn't do anything. Has anyone else encountered this issue?

**Comment by BradFitz66** [comment]
Updated to the latest commit. It seems there's less artifacts but seems to be cropping a few pixels from the sides? 

![image](https://user-images.githubusercontent.com/28825575/176788864-e7bee684-39f1-48cd-b0f8-41ea7d9e94ad.png)

It also seems to (still) be using linear filtering, shouldn't it be nearest to preserve old 'sharp' pixel aesthetic? Trying to change it from outside bracket-bevy with an EventReader looking for asset events seems to not work although it does seem to be changing stuff.

**Comment by thebracket** [comment]
I really should have remembered to branch. Home with unwell baby, that was
meant to go to a branch for continuation on a nicer computer. Oops.
Bevy changed the image sampler setup. Look at fix-image.rs to see how to
change it

**Comment by BradFitz66** [comment]
I checked to see if changing to nearest_filter would work, but it doesn't actually seem to change it to linear filtering but did introduce the artifacts back

**Comment by thebracket** [comment]
As soon as the little one stops projectile vomiting, I'll explore the new
material shader interface. Looks promising. I'd like to go to the model I
used for OpenGL, which renders a single quad and selects glyphs and colors
from buffers. Not sure how practical that is, yet + but it looks a lot more
practical than when I started!

**Comment by thebracket** [comment]
I just pushed a fix. It turns out that you can't read an asset stream anymore when loading images and expect to be able to modify them. Not sure why, but changing the sampler descriptor wasn't doing anything. So I hacked up a system that repeatedly tries to get mutable access to fonts, and stops once it has them all - and then hits them with a full wgpu sampler descriptor that worked in the wgpu back-end of the main bracket-lib.

That solved some of the problem.

Then I had an "aha" moment, and realized that Bevy had enabled MSAA (multi-sampling) behind my back. Turning it off (setting samples to 1) reduced the GPU load massive on small systems, and got the white lines were mostly gone. Add a tiny "nudge factor", and it looks pretty good on my monster work system. 

![image](https://user-images.githubusercontent.com/14896751/176939275-a12c7c4b-516e-4003-810b-cb4bba0e5697.png)

So I think that one's at least triaged for now.

**Comment by BradFitz66** [comment]
![image](https://user-images.githubusercontent.com/28825575/176948165-ec47b3cc-aff2-4d8b-95ed-b434d95d12fe.png)
Yep, seems to be perfect now. Thanks!
